stages:
  install:
    cmd: python3 -m venv venv && . venv/bin/activate && pip install -U pip wheel setuptools && pip install -r requirements.txt && cp requirements.txt venv-installed
    deps:
    - requirements.txt
    outs:
    - venv-installed:
        cache: false
  load-vocab:
    cmd: annif load-vocab ykl corpora/ykl-skos.ttl
    deps:
    - venv-installed
    - corpora/ykl-skos.ttl
    outs:
    - data/vocabs/ykl
  train-omikuji-parabel-fi:
    cmd: annif train ykl-omikuji-parabel-fi -j 8 corpora/kirjaesittelyt2021/kvesit-ykl-fin-train.tsv
    params:
    - projects.toml:
      - ykl-omikuji-parabel-fi
    deps:
    - venv-installed
    - corpora/kirjaesittelyt2021/kvesit-ykl-fin-train.tsv
    - data/vocabs/ykl
    outs:
    - data/projects/ykl-omikuji-parabel-fi
  eval-omikuji-parabel-fi:
    cmd: annif eval ykl-omikuji-parabel-fi -j 8 -m Precision@1 -m NDCG --metrics-file
      reports/test-omikuji-parabel-fi.json corpora/kirjaesittelyt2021/kvesit-ykl-fin-test.tsv
    deps:
    - venv-installed
    - corpora/kirjaesittelyt2021/kvesit-ykl-fin-test.tsv
    - data/projects/ykl-omikuji-parabel-fi
    metrics:
    - reports/test-omikuji-parabel-fi.json:
        cache: false
  train-omikuji-bonsai-fi:
    cmd: annif train ykl-omikuji-bonsai-fi -j 8 corpora/kirjaesittelyt2021/kvesit-ykl-fin-train.tsv
    params:
    - projects.toml:
      - ykl-omikuji-bonsai-fi
    deps:
    - venv-installed
    - corpora/kirjaesittelyt2021/kvesit-ykl-fin-train.tsv
    - data/vocabs/ykl
    outs:
    - data/projects/ykl-omikuji-bonsai-fi
  eval-omikuji-bonsai-fi:
    cmd: annif eval ykl-omikuji-bonsai-fi -j 8 -m Precision@1 -m NDCG --metrics-file
      reports/test-omikuji-bonsai-fi.json corpora/kirjaesittelyt2021/kvesit-ykl-fin-test.tsv
    deps:
    - venv-installed
    - corpora/kirjaesittelyt2021/kvesit-ykl-fin-test.tsv
    - data/projects/ykl-omikuji-bonsai-fi
    metrics:
    - reports/test-omikuji-bonsai-fi.json:
        cache: false
