stages:
  install:
    cmd: python3 -m venv venv && . venv/bin/activate && pip install -U pip wheel setuptools && pip install -r requirements.txt && cp requirements.txt venv-installed
    deps:
    - requirements.txt
    outs:
    - venv-installed:
        cache: false
  load-vocab:
    cmd: annif load-vocab ykl corpora/ykl-skos.ttl
    deps:
    - venv-installed
    - corpora/ykl-skos.ttl
    outs:
    - data/vocabs/ykl
  train-omikuji-parabel:
    foreach:
      - lang2: fi
        lang3: fin
      - lang2: sv
        lang3: swe
      - lang2: en
        lang3: eng
    do:
      cmd: annif train ykl-omikuji-parabel-${item.lang2} -j 8 corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-train.tsv
      params:
      - projects.toml:
        - ykl-omikuji-parabel-${item.lang2}
      deps:
      - venv-installed
      - corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-train.tsv
      - data/vocabs/ykl
      outs:
      - data/projects/ykl-omikuji-parabel-${item.lang2}
  eval-omikuji-parabel:
    foreach:
      - lang2: fi
        lang3: fin
      - lang2: sv
        lang3: swe
      - lang2: en
        lang3: eng
    do:
      cmd: annif eval ykl-omikuji-parabel-${item.lang2} -j 8 -m Precision@1 -m NDCG
        --metrics-file reports/test-omikuji-parabel-${item.lang2}.json
        --results-file reports/test-omikuji-parabel-${item.lang2}.csv
        corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-test.tsv
      deps:
      - venv-installed
      - corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-test.tsv
      - data/projects/ykl-omikuji-parabel-${item.lang2}
      outs:
      - reports/test-omikuji-parabel-${item.lang2}.csv:
          cache: false
      metrics:
      - reports/test-omikuji-parabel-${item.lang2}.json:
          cache: false
  train-omikuji-bonsai:
    foreach:
      - lang2: fi
        lang3: fin
      - lang2: sv
        lang3: swe
      - lang2: en
        lang3: eng
    do:
      cmd: annif train ykl-omikuji-bonsai-${item.lang2} -j 8 corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-train.tsv
      params:
      - projects.toml:
        - ykl-omikuji-bonsai-${item.lang2}
      deps:
      - venv-installed
      - corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-train.tsv
      - data/vocabs/ykl
      outs:
      - data/projects/ykl-omikuji-bonsai-${item.lang2}
  eval-omikuji-bonsai:
    foreach:
      - lang2: fi
        lang3: fin
      - lang2: sv
        lang3: swe
      - lang2: en
        lang3: eng
    do:
      cmd: annif eval ykl-omikuji-bonsai-${item.lang2} -j 8 -m Precision@1 -m NDCG
        --metrics-file reports/test-omikuji-bonsai-${item.lang2}.json
        --results-file reports/test-omikuji-bonsai-${item.lang2}.csv
        corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-test.tsv
      deps:
      - venv-installed
      - corpora/kirjaesittelyt2021/kvesit-ykl-${item.lang3}-test.tsv
      - data/projects/ykl-omikuji-bonsai-${item.lang2}
      outs:
      - reports/test-omikuji-bonsai-${item.lang2}.csv:
          cache: false
      metrics:
      - reports/test-omikuji-bonsai-${item.lang2}.json:
          cache: false
