[ykl-omikuji-parabel-fi]
name="YKL Omikuji Parabel Finnish"
language="fi"
backend="omikuji"
analyzer="voikko(fi)"
vocab="ykl"
ngram=1
min_df=1
access="hidden"

[ykl-omikuji-bonsai-fi]
name="YKL Omikuji Bonsai Finnish"
language="fi"
backend="omikuji"
cluster_balanced = "False"
cluster_k = 100
max_depth = 3
analyzer="voikko(fi)"
vocab="ykl"
ngram=1
min_df=1
access="hidden"

[ykl-omikuji-parabel-sv]
name="YKL Omikuji Parabel Swedish"
language="sv"
backend="omikuji"
analyzer="snowball(swedish)"
vocab="ykl"
ngram=1
min_df=1
access="hidden"

[ykl-omikuji-bonsai-sv]
name="YKL Omikuji Bonsai Swedish"
language="sv"
backend="omikuji"
cluster_balanced = "False"
cluster_k = 100
max_depth = 3
analyzer="snowball(swedish)"
vocab="ykl"
ngram=1
min_df=1
access="hidden"

[ykl-omikuji-parabel-en]
name="YKL Omikuji Parabel English"
language="en"
backend="omikuji"
analyzer="snowball(english)"
vocab="ykl"
ngram=1
min_df=1
access="hidden"

[ykl-omikuji-bonsai-en]
name="YKL Omikuji Bonsai English"
language="en"
backend="omikuji"
cluster_balanced = "False"
cluster_k = 100
max_depth = 3
analyzer="snowball(english)"
vocab="ykl"
ngram=1
min_df=1
access="hidden"

[ykl-fi]
name="YKL suomi"
language="fi"
backend="ensemble"
vocab="ykl"
sources="ykl-omikuji-parabel-fi,ykl-omikuji-bonsai-fi"

[ykl-sv]
name="KAB svenska"
language="sv"
backend="ensemble"
vocab="ykl"
sources="ykl-omikuji-parabel-sv,ykl-omikuji-bonsai-sv"

[ykl-en]
name="PLC English"
language="en"
backend="ensemble"
vocab="ykl"
sources="ykl-omikuji-parabel-en,ykl-omikuji-bonsai-en"
